name: Build

on: push

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v1
            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - name: Install
              run: npm i
            - name: Lint
              run: npm run lint
            - name: Tests
              run: npm t
              env:
                  CLIENTTESTS_XRAY_URL: ${{ secrets.XRAY_URL }}
                  CLIENTTESTS_XRAY_USERNAME: ${{ secrets.XRAY_USERNAME }}
                  CLIENTTESTS_XRAY_PASSWORD: ${{ secrets.XRAY_PASSWORD }}
