name: Build

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      # Prerequisites
      - uses: actions/checkout@v1
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # Install project
      - name: Install
        run: npm i

      # Run lint
      - name: Lint
        run: npm run lint

      # Run tests
      - name: Basic Auth Tests
        run: npm t
        env:
          CLIENTTESTS_PLATFORM_URL: ${{ secrets.CLIENTTESTS_PLATFORM_URL }}
          CLIENTTESTS_PLATFORM_USERNAME: ${{ secrets.CLIENTTESTS_PLATFORM_USERNAME }}
          CLIENTTESTS_PLATFORM_PASSWORD: ${{ secrets.CLIENTTESTS_PLATFORM_PASSWORD }}
      - name: Access Token Tests
        run: npm t
        env:
          CLIENTTESTS_PLATFORM_URL: ${{ secrets.CLIENTTESTS_PLATFORM_URL }}
          CLIENTTESTS_PLATFORM_ACCESS_TOKEN: ${{ secrets.CLIENTTESTS_PLATFORM_ACCESS_TOKEN }}

      # Send tests coverage to Codecov
      - name: Send code coverage
        uses: codecov/codecov-action@v2
        if: runner.os == 'Linux'
